setting:
  name: "test_kitti"
  output_root: "./experiments"
  pc_path: "./data/kitti/sequences/00/velodyne"
  pose_path: "./data/kitti/poses/00.txt"
  calib_path: "./data/kitti/sequences/00/calib.txt"
  kitti_correct: True
  correct_deg: 0.195
process:
  min_range_m: 3.0
  max_range_m: 80.0
  vox_down_m: 0.08
  min_z_m: -3.5
sampler:
  surface_sample_range_m: 0.25 
  surface_sample_n: 4
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  voxel_size_m: 0.4
  feature_dim: 8 
  query_nn_k: 6
  search_alpha: 0.2
  weighted_first: False
decoder:
  freeze_after_frame: 40
loss:
  main_loss_type: bce
  sigma_sigmoid_m: 0.08
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
tracker:
  source_vox_down_m: 0.6
  iter_n: 100
  GM_grad: 0.1 
  GM_dist: 0.2 
pgo:
  pgo_freq_frame: 20
  context_cosdist: 0.3
optimizer: # mapper
  batch_size: 16384
eval:
  wandb_vis_on: False # log to wandb or not
  o3d_vis_on: True # visualize the mapping or not
  silence_log: True # output the logs or not
  sensor_cad_path: ./cad/kitti_car.ply
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 9
  save_map: True